language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
    - php: 7.0
      env: CODE_ANALYSIS=yes
  allow_failures:
    - env: CODE_ANALYSIS=yes

addons:
  apt:
    packages:
      - parallel

sudo: false

script:
   - >
     echo "Running php lint";
     find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

   - >
     if [[ "$CODE_ANALYSIS" == "yes" ]]; then
       composer require typo3/cms="^7.6"
       git checkout composer.json
       .Build/bin/phpstan analyse --level 5 ext_localconf.php ext_tables.php Classes
     fi
